# target: 192.168.1.137 # replace with your Monitor IP
sources:
  - giest:
      host: "http://192.168.1.3"
      device_id: "3CBE0BE5851900C3"
      plugs:
        # Direct power reporting example
        - VMWare:
            mac: 53:75:31:f6:6a:01
            alias: "Filament Dryer"
            outlet_num: 0
        - Plex:
            mac: 53:75:31:f6:6a:02
            alias: "3D Printer"
            outlet_num: 8
  - giest:
      host: "http://192.168.1.146"
      device_id: "A86B930C851900C3"
      plugs:
        # Direct power reporting example
        - VMWare:
            mac: 53:75:31:f6:4d:01
            alias: "VMWare"
            outlet_num: 0
        - Plex:
            mac: 53:75:31:f6:4d:02
            alias: "Plex"
            outlet_num: 3
        - Fan:
            mac: 53:75:31:f6:4d:03
            alias: "Server Fan"
            outlet_num: 5
        - CBS4:
            mac: 53:75:31:f6:4d:04
            alias: "CBS4"
            outlet_num: 11
        - Router:
            mac: 53:75:31:f6:4e:01
            alias: "Asus Router"
            outlet_num: 4
        - Monitor:
            mac: 53:75:31:f6:4e:02
            alias: "Server Monitor"
            outlet_num: 9
        - Firewall:
            mac: 53:75:31:f6:4e:03
            alias: "Firewall"
            outlet_num: 10
  - aggregate:
      plugs:
        - agg1:
          alias: "Server Aggregate"
          mac: 50:c7:bf:f6:4e:01
          # Specify plug ID values (keys) to aggregate and report as a single value
          # Aggregate plug will update dynamically as the element reported powers change!
          # Useful to stay under the ~20 plug Sense limit
          elements:
            - Router
            - Firewall
        